-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 20:27:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cities_Countries1_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Countries1`
    FOREIGN KEY (`id_country`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `landing_track_longitude` DOUBLE NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Airports_Cities1_idx` (`id_city` ASC) VISIBLE,
  CONSTRAINT `fk_Airports_Cities1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `passengers_capacity` INT NOT NULL,
  `fuel_capacity` DOUBLE NULL,
  `id_owner` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planes_Airlines1_idx` (`id_owner` ASC) VISIBLE,
  CONSTRAINT `fk_Planes_Airlines1`
    FOREIGN KEY (`id_owner`)
    REFERENCES `mydb`.`Airlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `cellphone` VARCHAR(45) NOT NULL,
  `id_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_type_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `fk_employee_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `mydb`.`Employee_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATETIME NULL,
  `cellphone` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `id_airport` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gates_Airports1_idx` (`id_airport` ASC) VISIBLE,
  CONSTRAINT `fk_Gates_Airports1`
    FOREIGN KEY (`id_airport`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_plane` INT NULL,
  `id_pilot1` INT NULL,
  `id_pilot2` INT NULL,
  `id_origin_gate` INT NULL,
  `id_destiny_gate` INT NULL,
  `arrive_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `id_plane_idx` (`id_plane` ASC) VISIBLE,
  INDEX `id_pilot1_idx` (`id_pilot1` ASC) VISIBLE,
  INDEX `id_pilot2_idx` (`id_pilot2` ASC) VISIBLE,
  INDEX `fk_Flys_Gates1_idx` (`id_origin_gate` ASC) VISIBLE,
  INDEX `fk_Flys_Gates2_idx` (`id_destiny_gate` ASC) VISIBLE,
  CONSTRAINT `fk_Flys_Planes1`
    FOREIGN KEY (`id_plane`)
    REFERENCES `mydb`.`Planes` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Flys_Pilots1`
    FOREIGN KEY (`id_pilot1`)
    REFERENCES `mydb`.`Pilots` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Flys_Pilots2`
    FOREIGN KEY (`id_pilot2`)
    REFERENCES `mydb`.`Pilots` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Flys_Gates1`
    FOREIGN KEY (`id_origin_gate`)
    REFERENCES `mydb`.`Gates` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Flys_Gates2`
    FOREIGN KEY (`id_destiny_gate`)
    REFERENCES `mydb`.`Gates` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Control_tower_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Control_tower_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `id_employee` INT NOT NULL,
  `id_flight` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ControlTowerLogs_Employee1_idx` (`id_employee` ASC) VISIBLE,
  INDEX `fk_ControlTowerLogs_Flys1_idx` (`id_flight` ASC) VISIBLE,
  CONSTRAINT `fk_ControlTowerLogs_Employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ControlTowerLogs_Flights1`
    FOREIGN KEY (`id_flight`)
    REFERENCES `mydb`.`Flights` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Licences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Licences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hangars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hangars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `id_airport` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Hangars_Airports1_idx` (`id_airport` ASC) VISIBLE,
  CONSTRAINT `fk_Hangars_Airports1`
    FOREIGN KEY (`id_airport`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inmigration_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inmigration_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `id_flight` INT NOT NULL,
  `id_passenger` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_fly_idx` (`id_flight` ASC) VISIBLE,
  INDEX `id_passenger_idx` (`id_passenger` ASC) VISIBLE,
  CONSTRAINT `fk_Inmigration_log_Passengers1`
    FOREIGN KEY (`id_passenger`)
    REFERENCES `mydb`.`Passengers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Inmigration_log_Flights1`
    FOREIGN KEY (`id_flight`)
    REFERENCES `mydb`.`Flights` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot_Licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot_Licence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_licence` INT NOT NULL,
  `id_pilot` INT NOT NULL,
  `expiration_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Licences_has_Pilots_Pilots1_idx` (`id_pilot` ASC) VISIBLE,
  INDEX `fk_Licences_has_Pilots_Licences1_idx` (`id_licence` ASC) VISIBLE,
  CONSTRAINT `fk_Licences_has_Pilots_Licences1`
    FOREIGN KEY (`id_licence`)
    REFERENCES `mydb`.`Licences` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Licences_has_Pilots_Pilots1`
    FOREIGN KEY (`id_pilot`)
    REFERENCES `mydb`.`Pilots` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `id_type_of_employee_autorized` INT NULL,
  `id_airport` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vehicle_Airports1_idx` (`id_airport` ASC) VISIBLE,
  INDEX `fk_Vehicle_Type_of_Employee1_idx` (`id_type_of_employee_autorized` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_Airports1`
    FOREIGN KEY (`id_airport`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_Type_of_Employee1`
    FOREIGN KEY (`id_type_of_employee_autorized`)
    REFERENCES `mydb`.`Employee_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Identifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Identifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Identifications_Countries1_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_Identifications_Countries1`
    FOREIGN KEY (`id_country`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passengers_has_Identifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passengers_has_Identifications` (
  `id_passenger` INT NOT NULL,
  `id_identification` INT NOT NULL,
  `expiration_date` DATE NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Passengers_has_Identifications_Identifications1_idx` (`id_identification` ASC) VISIBLE,
  INDEX `fk_Passengers_has_Identifications_Passengers1_idx` (`id_passenger` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Passengers_has_Identifications_Passengers1`
    FOREIGN KEY (`id_passenger`)
    REFERENCES `mydb`.`Passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passengers_has_Identifications_Identifications1`
    FOREIGN KEY (`id_identification`)
    REFERENCES `mydb`.`Identifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
